---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: postgres-backup
  namespace: postgres
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: gcp-store
  target:
    name: postgres-backup-secret
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: postgres-gcs