---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: postgres-backup
  namespace: postgrees
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: gcp-store
  target:
    name: postgres-backup-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      gcs-key.json: 
        - secretKey: secret
          remoteRef: 
            key: postgres-gcs