---
apiVersion: postgres-operator.crunchydata.com/v1beta1
kind: PostgresCluster
metadata:
  name: pg-data
  namespace: postgres
spec:
  postgresVersion: 16
  instances:
    - name: data
      metadata:
        labels:
          app: pg-data
      dataVolumeClaimSpec:
        storageClassName: postgres-class
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 15Gi
  users:
    - name: postgres
      databases:
        - postgres
      options: "SUPERUSER"
      password:
        type: AlphaNumeric
    - name: vikunja
      databases:
        - vikunja
      password:
        type: AlphaNumeric
      options: "SUPERUSER"
  patroni:
    dynamicConfiguration:
      synchronous_mode: true
      postgresql:
        synchronous_commit: "on"
        pg_hba:
          #- hostnossl all all 10.42.0.0/16 md5
          #- hostssl all all all md5
          - host all all 0.0.0.0/0 md5
  backups:
    pgbackrest:
      configuration:
        - secret:
            name: postgres-backup-secret
      global:
        archive-push-queue-max: 4GiB
        repo1-retention-full: "2"
        repo1-path: "/pgbackrest/crunchy-pgo/pg-data/repo1"
        repo1-gcs-key: postgres-backup-secret
      repos:
        - name: repo1
          schedules:
            full: "0 0 1,7,8,15 * *"
            differential: "0 0 1,7,8,15 * *"
          gcs:
            bucket: aegiru-postgres