---
apiVersion: postgres-operator.crunchydata.com/v1beta1
kind: PostgresCluster
metadata:
  name: pg-data
  namespace: postgres
spec:
  postgresVersion: 16
  instances:
    - name: pg-data
      metadata:
        labels:
          app: pg-data
      dataVolumeClaimSpec:
        storageClassName: postgres-data
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 5Gi
      walVolumeClaimSpec:
        storageClassName: postgres-data
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 5Gi
  users:
    - name: postgres
      databases:
        - postgres
      options: "SUPERUSER"
      password:
        type: AlphaNumeric
    - name: vikunja
      databases:
        - vikunja
      password:
        type: AlphaNumeric
  backups:
    pgbackrest:
      configuration:
        - secret:
            name: postgres-backup-secret
      global:
        archive-push-queue-max: 4GiB
        repo1-retention-full: "2"
        repo1-path: "/pg/repo1"
      repos:
        - name: repo1
          schedules:
            full: "0 0 1,7,8,15 * *"
            differential: "0 0 1,7,8,15 * *"
          gcs:
            bucket: aegiru-postgres