---
apiVersion: postgres-operator.crunchydata.com/v1beta1
kind: ghcr.io/cloudnative-pg/postgresql:16.0-4Cluster
metadata:
  name: pg-data
  namespace: postgres
spec:
  postgresVersion: 16
  instances:
    - name: pg-data
      metadata:
        labels:
          app: pg-data
      dataVolumeClaimSpec:
        storageClassName: local-storage
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 5Gi
  users:
    - name: postgres
      databases:
        - postgres
      options: "SUPERUSER"
      password:
        type: AlphaNumeric
    - name: vikunja
      databases:
        - vikunja
      password:
        type: AlphaNumeric
    
