---
apiVersion: postgres-operator.crunchydata.com/v1beta1
kind: PostgresCluster
metadata:
  name: pg-data
  namespace: postgres
spec:
  postgresVersion: 16
  instances:
    - name: pg-data
      metadata:
        labels:
          app: pg-data
      dataVolumeClaimSpec:
        storageClassName: local-storage
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 5Gi
  users:
    - name: postgres
      databases:
        - postgres
      options: "SUPERUSER"
      password:
        type: AlphaNumeric
    - name: vikunja
      databases:
        - vikunja
      password:
        type: AlphaNumeric
  backups:
    pgbackrest:
      repository:
        configuration:
          - secret:
              name: postgres-backup-secret
              key: secret
        gcs:
          bucket: aegiru-postgres
          path: pg-data
          storageType: gcs
          verifyPgBackrest: true
      schedule: "0 0 1,8,15,22 * *"
      storageType: gcs
