---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: "postgres-data"
  namespace: "postgres"
spec:
  storageClassName: "local-storage"
  accessModes: ["ReadWriteMany"]
  resources:
    requests:
      storage: 10Gi
