---
# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: postgres-superuser
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: gcp-store
  target:
    name: postgres-secret
    template:
      engineVersion: v2
  data:
    - secretKey: username
      remoteRef:
        key: postgres_user
    - secretKey: password
      remoteRef:
        key: postgres_pass