---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: crunchydata
  namespace: flux-system
spec:
  interval: 1h0s
  timeout: 3m0s
  type: oci
  url: oci://registry.developers.crunchydata.com/crunchydata