apiVersion: v1
kind: Secret
metadata:
    name: cloudflared-secret
stringData:
    TUNNEL_ID: ENC[AES256_GCM,data:vFdg6LXIbTGXdu/6VcKewhuVswKl5xDu8pIPC6JkbXJIUd9f,iv:vo7nU8qQW/1o4x19/lUmzfnKEIY3x+7CALv9hWnmQc0=,tag:cNznCbluO2WpguOVRbigVw==,type:str]
    credentials.json: ENC[AES256_GCM,data:v3aQmBtCMj8rH6VHlUjAmCn8pduhlEjQ2fF/XMSd2tZEtvb17FUKifr/vEnGSIU+exF7aeRIe2h5Bx0fLM8ju2WZ66XROwrkpQEmYMdkTqpI3mGrGVahFoDrNsf7xE8bdwV/33P/a5bvc/F+zM6qOzQ890Kq2gXdrCKaoHkQSj5uK1Y8a0ZiP1N/ASkN80n9zq826/MviG+TqHEroaXriqyIvhgc1ip5lMtDKLn4vw==,iv:FukM+QvPoewgSrm0jep+qQEaIIilAyM2Cq27pHNWZ2s=,tag:a2QnaIF4fAVL++j1lx0Z+A==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1m7vemmhppt2j5lxuq3z3sqdfxjpgw3f5a0lx9c4g9ghn3kq4u5mssl6svw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlMWhsbmxyTThVSkFxS3Vu
            dkFyRnNKbEpBZG4xaXUwT1hCanUyeTVrOEJVCmN0QVpoNWpORXh2VUU2TmU0R1dH
            Z2l2V29iK1Z5RzdQQWo5aStidXJkSm8KLS0tIEZiNzdCQzJYb01ZS2dhdFVDTjhx
            MUptbzZJUkZGWmVxUDFDYXhrSVJZcXMKEtwRFcpyFiMg9FFxbbrhhBVoTNYJGdBu
            7l6L5cjltP7hiYHXeNPUigUZwFQfenZKafp0w8vonsUGaXe3bx4CQg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-03-05T18:00:06Z"
    mac: ENC[AES256_GCM,data:ZwHKVcEgLH7DcYbcbHEq6OuyoHan3FSYk/mHKW0jUNTzTUx7z15HjJRd48vUqqpp9e6zeoj88DNH1SrTInqYwF0rrCmTu1idCOvyHE26JmGwsGF8HM67G6FW/hNq4aBDwrrOZIlZ9Rj4HdDYh+pQl1jIJf6aoyJBnojEpVX6Yis=,iv:ddjo1dt1kYXzK0L7yZSRe4Z5Yx6wURYDGI/NrzvySBM=,tag:mf3dOHgAQxlGJsjHjeeN4Q==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
