---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: &app vikunja
  namespace: vikunja
spec:
  interval: 15m
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  chart:
    spec:
      chart: app-template
      version: 2.6.0
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
      interval: 15m
  values:
    controllers:
      main:
        containers:
          main:
            image:
              repository: vikunja/api
              tag: 0.22.1
            env:
              - name: VIKUNJA_SERVICE_TIMEZONE
                value: "Europe/Amsterdam"
              - name: VIKUNJA_DATABASE_TYPE
                value: "postgres"
              - name: VIKUNJA_DATABASE_HOST
                valueFrom:
                  secretKeyRef:
                    name: pg-data-pguser-vikunja
                    key: host
              - name: VIKUNJA_DATABASE_USER
                valueFrom:
                  secretKeyRef:
                    name: pg-data-pguser-vikunja
                    key: user
              - name: VIKUNJA_DATABASE_PASSWORD
                valueFrom:
                  secretKeyRef:
                    name: pg-data-pguser-vikunja
                    key: password
              - name: VIKUNJA_DATABASE_DATABASE
                valueFrom:
                  secretKeyRef:
                    name: pg-data-pguser-vikunja
                    key: dbname
            volumeMounts:
              # - name: files
              #   globalMounts:
              #     - path: /app/vikunja/files
              - name: config
                globalMounts:
                  - path: /app/vikunja/config.yaml
                    subPath: config.yaml
                    readOnly: true
            resources:
              requests:
                cpu: 10m
                memory: 183M
              limits:
                memory: 1269M
          frontend:
            image:
              repository: vikunja/frontend
              tag: 0.22.1
            env:
              - name: VIKUNJA_ALLOW_ICON_CHANGES
                value: "false"
            resources:
              requests:
                cpu: 11m
                memory: 35M
              limits:
                memory: 35M
    service:
      main:
        ports:
          http:
            port: 8080
    ingress:
      main:
        enabled: true
        className: "external"
        annotations:
          external-dns.alpha.kubernetes.io/target: "external.${SECRET_DOMAIN}"
        hosts:
          - host: &host "{{ .Release.Name }}.${SECRET_DOMAIN}"
            paths:
              - path: /
                service:
                  name: main
                  port: http
        tls:
          - hosts:
              - *host
    persistence:
      vikunja-config:
        enabled: true
        type: configMap
        name: vikunja
        globalMounts:
          - path: /etc/vikunja/config.yaml
            subPath: config.yaml