---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app vikunja
  namespace: flux-system
spec:
  dependsOn:
    - name: pg-app
    - name: pg-database
  path: ./kubernetes/apps/vikunja/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-kubernetes
  healthChecks:
    - apiVersion: helm.toolkit.fluxcd.io/v2beta1
      kind: HelmRelease
      name: vikunja
      namespace: collaboration
  interval: 30m
  retryInterval: 1m
  timeout: 3m