apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_EXAMPLE: ENC[AES256_GCM,data:kYQPRONSVZNXzXNsmuu7FQXEhBukZYVkjaarlBtHbX7/vy880f+sS1+SyNYeK1VG9AGNbEeLZYfrowTacD5peQLnedNdPFEeUeoKYy6EQEZFiwnOm/uiWg2CMz/J6A==,iv:jojP58uhqutO61lFf+sXgpUrPeQ9tavwNqsjrTQDZSI=,tag:eNAKvvoYiiEUrs3EzHxIJg==,type:str]
    SECRET_DOMAIN: ENC[AES256_GCM,data:L8epMmxRCS5e1XiKYw==,iv:z0IsDeXr4SY1oc6YHtswfk95WbBCDFjYKEhf0rRWRKg=,tag:kYQpYfm8T431pK3UK0ndyA==,type:str]
    SECRET_ACME_EMAIL: ENC[AES256_GCM,data:Oo2yFP9UKTxgKLpZ5NSlAs1HLsM=,iv:pBrr/B8Uwgwk3dRSt85J9Dcq0zNVPtjt1pJHe1R4iGc=,tag:UTnHEK1tq9rOJc121Ouq8A==,type:str]
    SECRET_CLOUDFLARE_TUNNEL_ID: ENC[AES256_GCM,data:TqSdvPGbrZcoeOS56KpT297sfYfgTa/LS/l/UQRTKzezWWpl,iv:MKRk4/qcVqI8w+8E2MomQaDDekbqhE401lWfKKno/XE=,tag:9yTC7HdGJhG+SCXNK7WwPA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1m7vemmhppt2j5lxuq3z3sqdfxjpgw3f5a0lx9c4g9ghn3kq4u5mssl6svw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnUXlUSkJyUGZMZ3BPaEJv
            YlZETytqNmZDUmtiYmhCMXcxcDlYd3E2aEdjCkk4YUoyOHFxVG5UZXQrRXZrSjFI
            UW5xQWVxdUVLRlJMT0NCTUFyWE4xZEkKLS0tIG50aWc4YTcxdElMWHVMTVVNSEhJ
            bFJIdjhiUHpnN01IVFNMNkFkQVNCVjgKsN836sM0hWfuQkLEDNo/9oAqasRSCKl7
            +eg+VzyBWCu5AZdzb1pnghgTSl193eQLL1OQDssDWvF1g4OsQH9qFg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-03-04T20:39:47Z"
    mac: ENC[AES256_GCM,data:l/H3X4uwxhObXjEurzW5L3G6wLkeoJ3Mu3ocfOXlvYuDR6w/GZwS40lateUipsDR/fJRwQojupT3Sec3nP5wtRXFORKhWu/NTw8qdnKcldgPUfnRTCVyi9w3b8mWMZdbdIm0H14DO3ilHYb8YU35D19HK7mdzq1PFKrESNLX7Ac=,iv:1FuVPC4uhZxpiFmIbG0/ckPwmbco2ECYBxDnt3tK2wo=,tag:dt5PwGqtlYIii9egoy/oRQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
