---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app pg-app
  namespace: flux-system
spec:
  targetNamespace: "postgres"
  path: ./kubernetes/apps/pg/app
  prune: false
  wait: false
  sourceRef:
    kind: GitRepository
    name: home-kubernetes
  interval: 30m
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: pg-database
  namespace: flux-system
spec:
  targetNamespace: "postgres"
  path: ./kubernetes/apps/pg/db
  dependsOn:
    - name: pg-app