apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
stringData:
    token: ENC[AES256_GCM,data:8FuANQ+YJxpoybKrmCt/h6QIFdjsVjBcCfRPAAACuBo=,iv:niyo3ybMAa2V7zmWCCKP4ESuNGWNh8F/SlWsMJVlc2w=,tag:e1Cq1irmIVX4Ny/9xG36nA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1m7vemmhppt2j5lxuq3z3sqdfxjpgw3f5a0lx9c4g9ghn3kq4u5mssl6svw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhMDZLMmQyTWw4bHJpV2tI
            UVBRSUJ0S1gvUVVIRlduU1RieTlsL0N4VkcwCm5DSTEyamZOZ0l1SUk1V2pBZUlx
            N1lsM2djQjY2REV6bWRuQTBTMUg1ZE0KLS0tIDJpUDZxOStsMjhpejFQWUhtRWRm
            TXMzLzA4UWQ3UVpzZkZBMHg0R2JUS2sKGr3c8bAHTbP0jEZSgOCiyzq26qy85XHC
            KAgUaJCXo+KwyBZYC1gnKrUqfCpgUy/BVRNDomxlXsF2JgdKwkK8aQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-03-05T07:58:49Z"
    mac: ENC[AES256_GCM,data:gq9mkUqhKZSieo9yQb1apEEbPTX4OMUfEEOmNMLNfq4onKoxYCKohk4goN2rFGZ/rzX5U+XeJoYBIT1JkgTkENqX9vgeDfZ7xpT5pCcXPLy2ynT+1lnmCeVDmYOyKP0CMdgI5RVJu5wJQOR+plHJTymX4Vx3XuWbpz2OmzqDaK4=,iv:gcO3MfCctpZkEVuNCsV6AkGaiRfmUTV5zssQQQOst6s=,tag:tADcPnYsvIMTHMC/JVRsiQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
