apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
stringData:
    token: ENC[AES256_GCM,data:YKFK20JT2+RKzg0QW8whBM5maHfiTI3030/xLZQPjsA=,iv:j5DUay0v6Tx33myCIIDyBlf1YZVqHhSzDOdKya1K5Pk=,tag:ZswNg5FeBIiAIzpCh4Psig==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1m7vemmhppt2j5lxuq3z3sqdfxjpgw3f5a0lx9c4g9ghn3kq4u5mssl6svw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1dFFDUTlueDdWTGlpWXNh
            MkgwWHpMUFNFSGl4YWpZVzVwNGZKR0FsZjNjClZaNXhCeVJ2UEo0cXVOcTBWTDFu
            MlJMRFFKa1FvYWlZelZ5R3NSY2pIZUkKLS0tIG9TRVc4TFRoUENLOUpjbDAwWlFL
            bEw0OG1QOTVCUXpHU1FQQ0tZQTNHa0EKK7EsRv0tsIGTAXcnAIDsNtLO7mUVLDMz
            g2fV5tiV0JWV2YtBAr5smMSARx6M4mgj5AQMqz6seEKi/Z5nWRkVSA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-03-05T18:06:40Z"
    mac: ENC[AES256_GCM,data:lb8D6sWDrr5AUGBOFMRrDXhAlA1C+YK6mycbVZVcKHBzUCjXm6T+F4s/kCx4FvSywGxMM8IOuwDEdVKlnDjjL7vzd/qZgs9myoWFKniip3OFPZapi6YOk1skMrw9aDOfHLmSEwHvtbTELUuGf0qurDYNOEebcAHMo8uXHx2a6F4=,iv:fpYTcSlPN1G7JHNgmwsm96T8K4OgQMDIsJi2H0x2bZE=,tag:70QPLLmMW1N4imEM0FgaLQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
