apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
stringData:
    token: ENC[AES256_GCM,data:A2ur2eLbEIRGGU80134WdGGgs/f/J1doOpOOdumH5lE=,iv:3uAjHjlQX64rrMldF5VQwpIBmfL/VruYup0KXGFNOd8=,tag:pxhtNNOBqaeg3j2ysv6m9Q==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1m7vemmhppt2j5lxuq3z3sqdfxjpgw3f5a0lx9c4g9ghn3kq4u5mssl6svw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIZ3ZPTE9DaHpmZ1BKOGdK
            bUZwaWRGcW1tMlA4K2hwOTZOVGpzSm5zRGpVCnplaktmV2pBVWtMd1RybnZnOFZK
            SDcwbm41WVgxSTY5QnJZUkZpWWc3SVEKLS0tIGpBRVVDbWY2V1pyQXVteXZXRUNk
            S0pmYy83K2dRYXd4Ny9HSUpOVFNLU1kKc06eyaDQ+l0CLJHhLHTheuY6NfZzELVZ
            XB0gNGnuTNHJoR8hVnG+MrD3CGf6QV4zTttatqQKLw9wQxxYlX5s9g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-03-04T20:39:47Z"
    mac: ENC[AES256_GCM,data:VSU7sD8Lzi7R6D/FggOQzWJEDPri2j0UPRt5KwxysF0r/joaOMZr2S76V3F4u3+1M9YYLrn5i5x/MrLTLxL5EFCHchLCJr/JgbJls5jSAAzHpxWwiaPQf4QzHaqffALNEEvtd7pWMBT/OuRNKoPFc6pynv5NEdLzSkwepBLfzAg=,iv:E2KqhMepCTl8lgFPJxi6mW/M1GW2RRHqz8Dy8WRZwis=,tag:zgD8DWp3QCAZVU7pgER4lA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
