apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
stringData:
    token: ENC[AES256_GCM,data:qGPVrXF5qziWhy1t8p66QNYXjZz87gWAdW1UZZIHGks=,iv:36u/88uA8mdsrAs1nWI2WzFQjbGYKUEJF1iNAZ5h1Yo=,tag:phrC0qUo6za3pWOzBMZCjg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1m7vemmhppt2j5lxuq3z3sqdfxjpgw3f5a0lx9c4g9ghn3kq4u5mssl6svw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAydGk0bHFCLzJqbngwOHI0
            OEphQnNDZUVxanlPUmcxT3JqZzhnb0dlZXl3Cjd6cmpPY1ZidHlTL0ZVZzJxOWNp
            TTI5ZGNDSUE2OUNIYUE3bDJwL3JQT3cKLS0tIFhzOGhhd1QwNGlTRUZvWkk5UTBT
            MFdOZjM0c2pCcVJDYUdLaFF3dFcvOVkKeTOvq9BYi2cZ1XuNSuZvLo5kP9+Xdvy1
            u9lM7NtunFmux9/D2n582IM/IcX4ETGlQ5rbA0r2NR6WnnJ9Wbt8eg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-03-05T18:00:06Z"
    mac: ENC[AES256_GCM,data:Wkz6cHSyb7SCEefNd1ovS8idUYeAoglD7i2Mt8KBYFIvrMqrn8p+K7wI+wpsYfsSNtmpABTTui6KMNrMYpa9T+xCssUqZ73QMRHuTaJ4e/20kEjIzuAM92K+GKKvm2QnF8YXqfVuZ5DKmaPdOwPh4hwEps8unIudF7bDNmmRn/c=,iv:i7Xn3dZAxpkfFyUOTqV6hmz4/PtnCCbzMgNQHBjpa18=,tag:rb1YlwqRubGUyP4+UZ1hiw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
