apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
stringData:
    token: ENC[AES256_GCM,data:Vup1pmzju593Kk6O39LNkZEc0ibZku7TkTyg0EJmuhA=,iv:cL4qjdT0Mm8LHHwMMzGstV7jEebHNuongBt8qZ4RCtQ=,tag:tvjRG/WlpYoZlyD1nrvK7Q==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1m7vemmhppt2j5lxuq3z3sqdfxjpgw3f5a0lx9c4g9ghn3kq4u5mssl6svw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHNUdqbTRNTDhLQ0ZRWFRy
            eDVPUCtLZVJnYVdROWhOazZGWGg5MGdtUW1jCmdiVEVRanp5NU5UQ3N6dVEzL1ZC
            bWIzbE42S05DNWxsd1JtbDdnNXVGL3cKLS0tIGdxV1F3QVBSaEh0cWwxYXlNc0lN
            bVJma2ZVUkJxUm1wOFB1SXhheis3ZGMKPXJBF/++UYYE6fmjNDN7y/4LoCszgpl9
            9mdLPVbA4fxmfb/1GwvcmyiJitfGayMM+sfLl8+kftTvAcFJfeOpgw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-03-05T22:58:05Z"
    mac: ENC[AES256_GCM,data:8/wghHiQTmmr4i2cVz061UD6J5zRD1TuYXcZmpGDvJ/ww3dvNaw1tRqnvqMF5ED21uFxEwKYkTi6rtjZpXhoYHC3to1rnW72fkg+RznS0HcNX0E4B/84VUMU/rTYe2c91alq+0JmM+unZ1zZk/KTe5PbdHMQ4ZpmqGhIX7MdEl0=,iv:XeSFVcncnEKBXpk+WY5rFHJIq5rLjbYa+OmqS/ItElI=,tag:HA+Z5avszStCoIgAMUy9tA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
