---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2beta2.json
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: code-server
  namespace: code-server
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 2.6.0
      sourceRef:
        name: bjw-s
        kind: HelmRepository
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    controllers:
      main:
        type: deployment
        replicas: 1
        containers:
          main:
            image:
              repository: ghcr.io/coder/code-server
              tag: "4.22.0"
            args: [
              "--auth", "none",
              "--disable-telemetry",
              "--bind-addr", "0.0.0.0:8080",
              "--port", "8080"
            ]
            env:
              TZ: "Europe/Amsterdam"
              SSH_AUTH_SOCK: ""
    service:
      main:
        ports:
          http:
            port: 8080
    serviceMonitor:
      main:
        enabled: true
    ingress:
      main:
        enabled: true
        className: external
        annotations:
          external-dns.alpha.kubernetes.io/target: "external.${SECRET_DOMAIN}"
        hosts:
          - host: &host "{{ .Release.Name }}.${SECRET_DOMAIN}"
            paths:
              - path: /
                service:
                  name: main
                  port: http
        tls:
          - hosts:
              - *host
    