---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: "code-server-data"
  namespace: "code-server"
spec:
  storageClassName: "local-storage"
  accessModes: ["ReadWriteOnce"]
  resources:
    requests:
      storage: 5Gi
