---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: "code-server-data-1"
  namespace: "code-server"
spec:
  storageClassName: "local-storage"
  accessModes: ["ReadWriteMany"]
  resources:
    requests:
      storage: 5Gi
