---
k3s_control_node: true
k3s_server:
  cluster-cidr: "30.0.69.0/24"
  service-cidr: "30.0.96.0/24"
  disable: ["flannel", "local-storage", "metrics-server", "servicelb", "traefik"]
  disable-cloud-controller: true
  disable-kube-proxy: true
  disable-network-policy: true
  docker: false
  embedded-registry: true
  etcd-expose-metrics: true
  flannel-backend: "none"
  kube-apiserver-arg:
    - "anonymous-auth=true"
  kube-controller-manager-arg:
    - "bind-address=0.0.0.0"
  kube-scheduler-arg:
    - "bind-address=0.0.0.0"
  kubelet-arg:
    - "image-gc-high-threshold=55"
    - "image-gc-low-threshold=50"
  node-ip: "{{ ansible_host }}"
  pause-image: registry.k8s.io/pause:3.9
  secrets-encryption: true
  tls-san:
    - "30.0.66.1"
  write-kubeconfig-mode: "644"
