apiVersion: v1
kind: Secret
metadata:
    name: external-dns-secret
stringData:
    api-token: ENC[AES256_GCM,data:ee0V1/LvOoDaZaauYVl1e7GTidSahtNbxxRpHnIucU2bbjNOp2Q9gQ==,iv:dPEn0tQjbQuNpd+dwZD+njO9Gu2PE17Tc9aYQ0ZxoRM=,tag:60c6YmH3jBk/khGb5HuZ9g==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1m7vemmhppt2j5lxuq3z3sqdfxjpgw3f5a0lx9c4g9ghn3kq4u5mssl6svw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3R05PeDM3SkllMFNUdm9P
            RFZHTlpxRzZRZUZoWGxnK1Y0TWxLaGtSeVFrCkRHMU9CQWNVU0todkNLbmdDSlRa
            Z0gxbkN1L2N6YUlkNGhKSUVHSWc5S3cKLS0tIHpBWTJ1aHZUTkVkbU1GUElZWDB1
            a2pBSkFQMlFMMzNKcDhpK3pXZ2ozSkUK4bKUCm1MgAn4PtBAmf+pkbrF6/gftyoY
            +Vwu5eDuLiWwWwGc5PAxUZg8nzSVtxlQfq0L9WqHvErZpofRV9ulLg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-03-05T18:06:40Z"
    mac: ENC[AES256_GCM,data:VCZY0qS2ffUnde20GnN9VYwxaNknCvxhrstsWkNE2O01cWkY0k3pplnlpksfxFSpTSK7rkyEBX2zYQGw6OxtvslaC0OlyBQ5vOVCOBi9Av5MtnL+0mIVmL9Mb2T94sC90fjKzSi168kjhEyB7NoKDQEyGZtSdHnasleHU38PSE8=,iv:9vsyhK9jnD2Rw0j8VNyvngVRrqczksknukObo20I36o=,tag:XrBNR1HVpAxFwiTrgG+TBg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
