apiVersion: v1
kind: Secret
metadata:
    name: external-dns-secret
stringData:
    api-token: ENC[AES256_GCM,data:PhCihEmmIM6Gw7DpvwaiQYbzvCVvcyY1i4GBkU/Zj086GljchT64xQ==,iv:UDy0h5h4UZzitn50hDrH7CJe2iD/DZyfteGp1MpnHLY=,tag:hHnUpnJSTPUi3gxP2EY/zA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1m7vemmhppt2j5lxuq3z3sqdfxjpgw3f5a0lx9c4g9ghn3kq4u5mssl6svw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJbjJYUnBGblRwTHJEb1hB
            c0dTWEJWM1BCb1dlNE1EVjVyRHZhRC9QNENNClFRTk9Pbjc4MGJoYXh5SVgzOXdy
            NGVvZmMrS3U1QzgwVitUOHp5emw0eHMKLS0tIHBiUjZqbTRSV212dCs4dTBwcjVU
            RDYyaDFZc1JjUXdIRjJXU2N1d0JGamcKCc13xSVByFTpond/r+6SYZfq+U+fCz+f
            JVbC4t7j4vxrge8A5KSW4BHKTLVmip75OqgBqQaKplKVOvmlysumIg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-03-05T18:30:48Z"
    mac: ENC[AES256_GCM,data:HDPHQnOHhjBu58hCprNg1JLIhAzY259mTSQ2jABko0mZMGZrUp3xA2bgkHZrvG4gWu7ELSBI2UKryiGBOeNU3P1ZsyX6Me5vxHmSxVK/jCQu1g+Q2c6zGkcQ/CzgHIS5J3MIho7YifpMNJXjLJWcekj+d2H3iut0QJ2frbYs3Ws=,iv:h3oyOPYOFIUKQW9IZAFU8v5zMdlUfkEnbZl6yscHmKc=,tag:Q48mhmVyn6PjP4a0Mv0XEw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
